export const API_ENDPOINTS = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    signout: "/auth/signout",
    switchWorkspace: "/auth/switch-workspace",
  },
  leads: {
    list: "/leads",
    create: "/leads",
    publicRegister: "/leads/public-register",
    dashboardStats: "/leads/dashboard/stats",
    allocate: "/leads/allocate",
    detail: (id: string) => `/leads/${id}`,
    update: (id: string) => `/leads/${id}`,
    uploadAttachment: (id: string) => `/leads/${id}/attachments`,
    executeAction: (id: string) => `/leads/${id}/execute-action`,
    clickButton: (id: string) => `/leads/${id}/click-button`,
    move: (id: string) => `/leads/${id}/move`,
    customers: "/leads/customers",
    customerDetail: (id: string) => `/leads/customers/${id}`,
    customerUpdate: (id: string) => `/leads/customers/${id}`,
    convert: (id: string) => `/leads/${id}/convert`,
  },
  queues: {
    list: "/queues",
    create: "/queues",
    detail: (id: string) => `/queues/${id}`,
    update: (id: string) => `/queues/${id}`,
    delete: (id: string) => `/queues/${id}`,
  },
  stages: {
    list: "/stages",
    create: "/stages",
    byQueue: (queueId: string) => `/stages/queue/${queueId}`,
    update: (id: string) => `/stages/${id}`,
    delete: (id: string) => `/stages/${id}`,
  },
  steps: {
    list: "/steps",
    create: "/steps",
    detail: (id: string) => `/steps/${id}`,
    update: (id: string) => `/steps/${id}`,
    delete: (id: string) => `/steps/${id}`,
    addButton: (stepId: string) => `/steps/${stepId}/buttons`,
    updateButton: (buttonId: string) => `/steps/buttons/${buttonId}`,
    createTransition: (buttonId: string) =>
      `/steps/buttons/${buttonId}/transitions`,
  },
  storage: {
    upload: "/storage/upload",
  },
  notifications: {
    sendEmail: "/notifications/send-email",
  },
  forms: {
    list: "/forms",
    create: "/forms",
    detail: (id: string) => `/forms/${id}`,
    update: (id: string) => `/forms/${id}`,
    delete: (id: string) => `/forms/${id}`,
    public: (id: string) => `/forms/public/${id}`,
    publicSubmit: (id: string) => `/forms/public/${id}/submit`,
    pwa: (token: string) => `/forms/pwa/${token}`,
  },
  workspaces: {
    list: "/workspaces",
    create: "/workspaces",
    detail: (id: string) => `/workspaces/${id}`,
    update: (id: string) => `/workspaces/${id}`,
    delete: (id: string) => `/workspaces/${id}`,
    uploadLogo: (id: string) => `/workspaces/${id}/logo`,
  },
  users: {
    me: "/users/me",
  },
} as const;
